name: Auto Sign PR Commits

on:
  pull_request:
    types: [opened, labeled, synchronize]

jobs:
  sign-commits:
    if: contains(github.event.pull_request.labels.*.name, 'figma-plugin')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}

      - name: Generate JWT
        id: generate_jwt
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get App Info
        id: app_info
        run: |
          response=$(curl -s \
            -H "Authorization: Bearer ${{ steps.generate_jwt.outputs.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/app")

          app_slug=$(echo "$response" | jq -r '.slug')
          echo "APP_SLUG=$app_slug" >> $GITHUB_OUTPUT
          echo "Found app slug: $app_slug"

      - name: Configure Git
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
          git config --global user.name "${{ steps.app_info.outputs.APP_SLUG }}[bot]"
          git config --global user.email "${{ vars.APP_ID }}+${{ steps.app_info.outputs.APP_SLUG }}[bot]@users.noreply.github.com"

      - name: Recommit with Original Authors
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
          # Create a temporary branch
          git checkout -b temp-branch

          # Reset to target commit
          git reset --hard ${{ github.event.pull_request.head.sha }}

          # Amend the commit to be signed by the bot while preserving author
          author_name=$(git log -1 --format="%an")
          author_email=$(git log -1 --format="%ae")
          author_date=$(git log -1 --format=%aI)
          commit_msg=$(git log -1 --format=%B)

          # Amend the commit
          GIT_AUTHOR_NAME="$author_name" \
          GIT_AUTHOR_EMAIL="$author_email" \
          GIT_AUTHOR_DATE="$author_date" \
          git commit --amend --no-edit

          # Force push back to the PR branch
          git push --force origin temp-branch:${{ github.event.pull_request.head.ref }}
