name: Auto Sign PR Commits

on:
  pull_request:
    types: [opened, labeled, synchronize]

jobs:
  sign-commits:
    # Check both the label and that the commit isn't already signed by our bot
    if: |
      contains(github.event.pull_request.labels.*.name, 'figma-plugin') && !endsWith(github.event.pull_request.head.sha.committer.email, '+${{ vars.APP_SLUG }}[bot]@users.noreply.github.com')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check commit author
        id: check_author
        run: |
          # Get the commit info
          response=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }})

          committer_email=$(echo "$response" | jq -r '.commit.committer.email')
          expected_bot_email="${{ vars.APP_ID }}+${{ vars.APP_SLUG }}[bot]@users.noreply.github.com"

          if [ "$committer_email" = "$expected_bot_email" ]; then
            echo "Commit is already signed by our bot, skipping"
            exit 0
          fi

          echo "SHOULD_SIGN=true" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        if: steps.check_author.outputs.SHOULD_SIGN == 'true'
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate App Token
        if: steps.check_author.outputs.SHOULD_SIGN == 'true'
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}

      - name: Configure Git
        if: steps.check_author.outputs.SHOULD_SIGN == 'true'
        run: |
          git config --global user.name "${{ vars.APP_SLUG }}[bot]"
          git config --global user.email "${{ vars.APP_ID }}+${{ vars.APP_SLUG }}[bot]@users.noreply.github.com"

      - name: Sign Latest Commit
        if: steps.check_author.outputs.SHOULD_SIGN == 'true'
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          # Get the latest commit info
          commit_msg=$(git log -1 --format=%B)
          tree_hash=$(git rev-parse HEAD^{tree})
          parent_hash=$(git rev-parse HEAD^1)

          # Create the commit using the GitHub API
          response=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/git/commits \
            -d "{
              \"message\":\"$commit_msg\",
              \"tree\":\"$tree_hash\",
              \"parents\":[\"$parent_hash\"]
            }")

          # Extract the new commit SHA
          new_commit_sha=$(echo "$response" | jq -r '.sha')

          if [ -z "$new_commit_sha" ] || [ "$new_commit_sha" = "null" ]; then
            echo "Failed to get new commit SHA"
            echo "API Response: $response"
            exit 1
          fi

          echo "Created new commit: $new_commit_sha"

          # Update the branch reference using the API
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }} \
            -d "{
              \"sha\":\"$new_commit_sha\",
              \"force\":true
            }"
