name: Auto Sign PR Commits

on:
  pull_request:
    types: [opened, labeled, synchronize]

jobs:
  sign-commits:
    if: contains(github.event.pull_request.labels.*.name, 'figma-plugin')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}

      - name: Configure Git
        run: |
          # Configure Git to use the App's identity
          git config --global user.name "${{ vars.APP_SLUG }}[bot]"
          git config --global user.email "${{ vars.APP_ID }}+${{ vars.APP_SLUG }}[bot]@users.noreply.github.com"
          git config --global commit.gpgsign true

          # Use the token for operations
          git remote set-url origin "https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/${{ github.repository }}"

      - name: Sign Latest Commit
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          # Get the latest commit info
          commit_msg=$(git log -1 --format=%B)
          tree_hash=$(git rev-parse HEAD^{tree})
          parent_hash=$(git rev-parse HEAD^1)

          # Create a new signed commit with the same tree
          git checkout --orphan temp-branch
          git reset --hard

          # Create the commit using the GitHub API to ensure proper signing
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/git/commits \
            -d "{
              \"message\":\"$commit_msg\",
              \"tree\":\"$tree_hash\",
              \"parents\":[\"$parent_hash\"]
            }"

          # Update the branch reference
          git push --force origin HEAD:${{ github.event.pull_request.head.ref }}
